# Generated by Django 6.0.6 on 2026-06-08 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing', models.CharField(choices=[('FORGE', 'The Forge'), ('HADASSAH', 'The Hadassah Project'), ('HUMANITARIAN', 'Humanitarian Wing')], max_length=20, unique=True)),
                ('tagline', models.CharField(max_length=160)),
                ('headline', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('accent', models.CharField(default='terracotta', help_text='terracotta | olive | gold', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=20)),
                ('suffix', models.CharField(blank=True, default='+', max_length=5)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('role', models.CharField(max_length=240)),
                ('featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('position', models.CharField(choices=[('GLOBAL_LEAD', 'Global Lead'), ('EXEC_DIRECTOR', 'Executive Director'), ('DIRECTOR', 'Director'), ('SECRETARY', 'Company Secretary')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('credential', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('kind', models.CharField(choices=[('CONFERENCE', 'Conference'), ('MENTORSHIP', 'Mentorship Cohort'), ('OUTREACH', 'Humanitarian Outreach'), ('WORKSHOP', 'Workshop / Gathering')], default='CONFERENCE', max_length=20)),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('location', models.CharField(default='Virtual Conference', max_length=160)),
                ('is_virtual', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('registration_open', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='pages.program')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
    ]
