# Generated by Django 6.0.6 on 2026-07-06 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms of Use'), ('donation', 'Donation Policy')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(help_text='Plain text / simple HTML. Placeholder content until final policy is supplied.')),
                ('is_placeholder', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=160)),
                ('author_role', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('CONFERENCE', 'Conference'), ('MENTORSHIP', 'Mentorship'), ('OUTREACH', 'Humanitarian Outreach')], default='CONFERENCE', max_length=20)),
                ('quote', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='flyer',
            field=models.ImageField(blank=True, null=True, upload_to='flyers/'),
        ),
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='speakers/'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='accent',
            field=models.CharField(default='coffee', help_text='coffee | tan | olive | gold', max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='wing',
            field=models.CharField(choices=[('FORGE', 'The Forge'), ('HADASSAH', 'The Hadassah Project'), ('HUMANITARIAN', 'Humanitarian Wing'), ('VIRTUAL', 'Virtual Conferences'), ('MENTORSHIP', 'Mentorship Programme')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery', to='pages.program')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('external_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='pages.program')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
