# Generated by Django 6.0.6 on 2026-07-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_policy_testimonial_event_flyer_program_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_font', models.CharField(choices=[('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Poppins', 'Poppins'), ('Source Sans 3', 'Source Sans 3'), ('Nunito Sans', 'Nunito Sans'), ('Work Sans', 'Work Sans'), ('Manrope', 'Manrope'), ('Raleway', 'Raleway'), ('Playfair Display', 'Playfair Display'), ('Lora', 'Lora'), ('Merriweather', 'Merriweather'), ('Oswald', 'Oswald'), ('Cormorant Garamond', 'Cormorant Garamond'), ('Libre Baskerville', 'Libre Baskerville'), ('DM Sans', 'DM Sans'), ('Urbanist', 'Urbanist'), ('Space Grotesk', 'Space Grotesk')], default='Inter', help_text='Google Font used for headings, display text, and brand marks.', max_length=80)),
                ('body_font', models.CharField(choices=[('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Poppins', 'Poppins'), ('Source Sans 3', 'Source Sans 3'), ('Nunito Sans', 'Nunito Sans'), ('Work Sans', 'Work Sans'), ('Manrope', 'Manrope'), ('Raleway', 'Raleway'), ('Playfair Display', 'Playfair Display'), ('Lora', 'Lora'), ('Merriweather', 'Merriweather'), ('Oswald', 'Oswald'), ('Cormorant Garamond', 'Cormorant Garamond'), ('Libre Baskerville', 'Libre Baskerville'), ('DM Sans', 'DM Sans'), ('Urbanist', 'Urbanist'), ('Space Grotesk', 'Space Grotesk')], default='Inter', help_text='Google Font used for paragraphs, tables, forms, and controls.', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site branding',
                'verbose_name_plural': 'Site branding',
            },
        ),
    ]
