# Generated by Django 6.0.6 on 2026-07-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_sitebranding'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accessibility',
            field=models.TextField(blank=True, help_text='Accessibility, interpretation, transport, or inclusion notes.'),
        ),
        migrations.AddField(
            model_name='event',
            name='agenda',
            field=models.TextField(blank=True, help_text='Public agenda or run of show. Use one agenda item per line.'),
        ),
        migrations.AddField(
            model_name='event',
            name='audience',
            field=models.TextField(blank=True, help_text='Who should attend. Use short paragraphs or bullet-style lines.'),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='online_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='outcomes',
            field=models.TextField(blank=True, help_text='What participants will leave with. Use one outcome per line.'),
        ),
        migrations.AddField(
            model_name='event',
            name='preparation',
            field=models.TextField(blank=True, help_text='What participants should bring, complete, or know before attending.'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_note',
            field=models.TextField(blank=True, help_text='Public note shown beside the registration form.'),
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.TextField(blank=True, help_text='Speaker/facilitator list. Use one person or role per line.'),
        ),
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.CharField(blank=True, help_text='Short public summary used on cards and event detail headers.', max_length=260),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_address',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
