# Generated by Django 6.0.6 on 2026-07-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_event_accessibility_event_agenda_event_audience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebranding',
            name='contact_email',
            field=models.EmailField(blank=True, default='hello@onesimusimpact.org', max_length=254),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='contact_phone',
            field=models.CharField(blank=True, default='+233 XXX XXX XXX', max_length=40),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='footer_blurb',
            field=models.TextField(blank=True, default='A youth-led NGO in Accra equipping emerging African leaders through conferences, mentorship, humanitarian action, and digital infrastructure.'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='founded_year',
            field=models.CharField(blank=True, default='2018', max_length=20),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='location',
            field=models.CharField(blank=True, default='Accra, Ghana', max_length=120),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='logo_mark',
            field=models.ImageField(blank=True, help_text='Compact square or circular logo mark used where space is limited.', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='org_name',
            field=models.CharField(blank=True, default='Onesimus Impact Foundation', help_text='Official public name of the organization or project.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='short_name',
            field=models.CharField(blank=True, default='OIF', help_text='Short label used in compact dashboard and browser contexts.', max_length=40),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='tagline',
            field=models.CharField(blank=True, default='Equipping the Next Generation of Global Leaders', max_length=180),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='X / Twitter profile URL.'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
