# Generated by Django 6.0.6 on 2026-08-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_seed_site_branding_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_hero', models.ImageField(blank=True, help_text='Homepage — full-width hero background behind the headline.', null=True, upload_to='page-images/')),
                ('about_hero', models.ImageField(blank=True, help_text='About OIF — hero photo beside the introduction.', null=True, upload_to='page-images/')),
                ('about_story', models.ImageField(blank=True, help_text='About OIF — photo beside the "Our story" section.', null=True, upload_to='page-images/')),
                ('programs_hero_main', models.ImageField(blank=True, help_text='Programs — large hero photo.', null=True, upload_to='page-images/')),
                ('programs_hero_alt1', models.ImageField(blank=True, help_text='Programs — small hero photo (first).', null=True, upload_to='page-images/')),
                ('programs_hero_alt2', models.ImageField(blank=True, help_text='Programs — small hero photo (second).', null=True, upload_to='page-images/')),
                ('impact_hero', models.ImageField(blank=True, help_text='Impact — hero photo.', null=True, upload_to='page-images/')),
                ('leadership_hero', models.ImageField(blank=True, help_text='Leadership — hero photo.', null=True, upload_to='page-images/')),
                ('speakers_hero', models.ImageField(blank=True, help_text='Speakers — hero photo.', null=True, upload_to='page-images/')),
                ('gallery_hero', models.ImageField(blank=True, help_text='Gallery — hero photo.', null=True, upload_to='page-images/')),
                ('donate_hero', models.ImageField(blank=True, help_text='Donate (information page) — hero photo.', null=True, upload_to='page-images/')),
                ('involved_mentor', models.ImageField(blank=True, help_text='Get Involved — mentor portrait.', null=True, upload_to='page-images/')),
                ('involved_volunteer', models.ImageField(blank=True, help_text='Get Involved — volunteer portrait.', null=True, upload_to='page-images/')),
                ('involved_partner', models.ImageField(blank=True, help_text='Get Involved — partner portrait.', null=True, upload_to='page-images/')),
                ('give_side', models.ImageField(blank=True, help_text='Give (donation checkout) — side photo.', null=True, upload_to='page-images/')),
                ('apply_side', models.ImageField(blank=True, help_text='Apply (mentor/volunteer/mentee/speaker) — side photo.', null=True, upload_to='page-images/')),
                ('auth_side', models.ImageField(blank=True, help_text='Login and password reset — side photo.', null=True, upload_to='page-images/')),
                ('signup_side', models.ImageField(blank=True, help_text='Create account — side photo.', null=True, upload_to='page-images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page imagery',
                'verbose_name_plural': 'Page imagery',
            },
        ),
    ]
