# Generated by Django 6.0.6 on 2026-08-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_seed_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepagecopy',
            name='contact_response_note',
            field=models.CharField(blank=True, help_text='Short response-time expectation shown beside the send button.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitepageimages',
            name='contact_hero',
            field=models.ImageField(blank=True, help_text='Contact — hero photo.', null=True, upload_to='page-images/'),
        ),
    ]
