# Generated by Django 6.0.6 on 2026-08-21 09:08

import django.db.models.deletion
from django.db import migrations, models


def seed_program_initiatives(apps, schema_editor):
    Initiative = apps.get_model('pages', 'ProgramInitiative')
    Session = apps.get_model('pages', 'MentorshipSession')
    Track = apps.get_model('pages', 'MentorshipTrack')

    rows = [
        {
            'slug': 'the-emerging-leader', 'pillar': 'CONFERENCES',
            'page_type': 'CONFERENCE', 'title': 'The Emerging Leader',
            'eyebrow': 'THE FORGE · VIRTUAL CONFERENCE',
            'description': "A biannual virtual conference bringing established leaders into conversation with young people rising into their generation's calling in business, public service, and beyond.",
            'frequency_badge': 'Organized Biannually', 'order': 1,
        },
        {
            'slug': 'the-emerging-lady', 'pillar': 'CONFERENCES',
            'page_type': 'CONFERENCE', 'title': 'The Emerging Lady',
            'eyebrow': 'THE HADASSAH PROJECT · VIRTUAL CONFERENCE',
            'description': 'A biannual virtual conference forming the next generation of young women through teaching, dialogue, and the voices of women who have gone before them.',
            'frequency_badge': 'Organized Biannually', 'order': 2,
        },
        {
            'slug': 'forge-mentorship-program', 'pillar': 'MENTORSHIP',
            'page_type': 'MENTORSHIP', 'title': 'Forge Mentorship Program',
            'eyebrow': 'THE FORGE · MENTORSHIP',
            'description': 'A two-phase mentorship cohort open to both males and females. Phase 1 covers 8 sessions — 4 on career development and 4 on entrepreneurship. In Phase 2, mentees are grouped into two tracks — career development and entrepreneurship — each with 4 live sessions with their assigned mentor.',
            'phase_one_title': 'Sessions (8 Sessions)',
            'phase_one_intro': 'The 8 sessions are split into two tracks: the first 4 cover career development, and the remaining 4 cover entrepreneurship. After completing the sessions, you will have a 30-minute live Q&A session with the mentor.',
            'phase_two_title': 'Mentor Groupings (Two Tracks)',
            'phase_two_intro': 'In Phase 2, mentees are grouped with a mentor by track. Some mentees are placed in the Career Development track and the rest in the Entrepreneurship track. Each track meets for 4 live sessions with its assigned mentor — for personalized guidance, accountability, and deeper engagement.',
            'order': 1,
        },
        {
            'slug': 'bloom-360-mentorship-program', 'pillar': 'MENTORSHIP',
            'page_type': 'MENTORSHIP', 'title': 'Bloom 360 Mentorship Program',
            'eyebrow': 'THE HADASSAH PROJECT · MENTORSHIP',
            'description': "OIF's signature mentorship initiative for young women, built around a two-phase, 12-week journey — structured to mirror the Forge Mentorship Program above, so both programs read as a matched pair on the site.",
            'phase_one_title': 'Sessions (8 Sessions / Weeks 1–8)',
            'phase_one_intro': "Over the first 8 weeks, participants take part in classroom-style sessions led by domain experts and guest speakers, combining teaching, group discussion, and practical exercises across the program's core growth pillars.",
            'phase_two_title': 'Mentor Pairing (Weeks 9–12)',
            'phase_two_intro': 'In the final 4 weeks, participants are paired one-on-one with a dedicated mentor for personalized guidance — including tailored career and spiritual advice, goal tracking, and accountability as they apply Phase 1 learning to their own lives and goals.',
            'order': 2,
        },
        {
            'slug': 'onesimus-community-outreach-initiative', 'pillar': 'EVENTS',
            'page_type': 'OUTREACH',
            'title': 'Onesimus Community Outreach Initiative (OCOI)',
            'eyebrow': 'HUMANITARIAN WING',
            'description': 'Our humanitarian arm channels our values into tangible community impact, focusing on education, youth empowerment, and sustainable development aligned with the UN SDGs.',
            'order': 1,
        },
        {
            'slug': 'in-person-events-and-gatherings', 'pillar': 'EVENTS',
            'page_type': 'IN_PERSON', 'title': 'In-Person Events & Gatherings',
            'eyebrow': 'IN-PERSON EVENTS',
            'description': 'Workshops, networking events, and community gatherings organized under the OIF banner across Ghana and beyond.',
            'order': 2,
        },
    ]
    created = {}
    for values in rows:
        slug = values['slug']
        obj, _ = Initiative.objects.update_or_create(slug=slug, defaults=values)
        created[slug] = obj

    forge = created['forge-mentorship-program']
    bloom = created['bloom-360-mentorship-program']
    for number in range(1, 9):
        Session.objects.get_or_create(
            initiative=forge, session_number=number,
            defaults={
                'title': 'Session title to be announced',
                'track_label': 'Career Development — Sessions 1–4' if number <= 4 else 'Entrepreneurship — Sessions 5–8',
                'order': number,
            },
        )
        Session.objects.get_or_create(
            initiative=bloom, session_number=number,
            defaults={'title': 'Session title to be announced', 'order': number},
        )

    Track.objects.get_or_create(
        initiative=forge, title='Career Development',
        defaults={
            'label': 'Track A', 'sessions_count': 4, 'order': 1,
            'description': 'Mentees focused on their professional path are grouped with a mentor for 4 live sessions on career direction, skills, and workplace readiness.',
        },
    )
    Track.objects.get_or_create(
        initiative=forge, title='Entrepreneurship',
        defaults={
            'label': 'Track B', 'sessions_count': 4, 'order': 2,
            'description': 'Mentees interested in entrepreneurship are grouped with a mentor for 4 live sessions on business modeling, execution, and growth.',
        },
    )
    Track.objects.get_or_create(
        initiative=bloom, title='One-to-one Mentor Pairing',
        defaults={
            'label': 'Weeks 9–12', 'sessions_count': 4, 'order': 1,
            'description': 'Participants meet with a dedicated mentor for tailored career and spiritual guidance, goal tracking, and accountability.',
        },
    )


def remove_program_initiatives(apps, schema_editor):
    Initiative = apps.get_model('pages', 'ProgramInitiative')
    Initiative.objects.filter(slug__in=[
        'the-emerging-leader', 'the-emerging-lady',
        'forge-mentorship-program', 'bloom-360-mentorship-program',
        'onesimus-community-outreach-initiative',
        'in-person-events-and-gatherings',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_sitepagecopy_contact_response_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming conference'), ('PAST', 'Past conference')], default='PAST', max_length=12)),
                ('edition_label', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateField(blank=True, null=True)),
                ('flyer', models.ImageField(blank=True, null=True, upload_to='conference-editions/')),
                ('registration_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['status', 'order', '-event_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('CONFERENCES', 'Virtual Conferences'), ('MENTORSHIP', 'Mentorship Program'), ('EVENTS', 'Events')], db_index=True, max_length=16)),
                ('page_type', models.CharField(choices=[('CONFERENCE', 'Virtual conference'), ('MENTORSHIP', 'Mentorship program'), ('OUTREACH', 'Humanitarian outreach'), ('IN_PERSON', 'In-person events')], db_index=True, max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('eyebrow', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('frequency_badge', models.CharField(blank=True, max_length=80)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='program-initiatives/')),
                ('phase_one_title', models.CharField(blank=True, max_length=180)),
                ('phase_one_intro', models.TextField(blank=True)),
                ('phase_two_title', models.CharField(blank=True, max_length=180)),
                ('phase_two_intro', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['pillar', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceSpeakerFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='conference-speakers/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_flyers', to='pages.conferenceedition')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('sessions_count', models.PositiveSmallIntegerField(default=4)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_tracks', to='pages.programinitiative')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InitiativeArchiveEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='program-archives/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_entries', to='pages.programinitiative')),
            ],
            options={
                'ordering': ['order', '-event_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='conferenceedition',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_editions', to='pages.programinitiative'),
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('track_label', models.CharField(blank=True, help_text='Optional grouping, e.g. Career Development or Entrepreneurship.', max_length=120)),
                ('video_url', models.URLField(blank=True, help_text='Stored for the future Watch feature; playback is not enabled yet.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_sessions', to='pages.programinitiative')),
            ],
            options={
                'ordering': ['order', 'session_number'],
                'constraints': [models.UniqueConstraint(fields=('initiative', 'session_number'), name='unique_initiative_session_number')],
            },
        ),
        migrations.CreateModel(
            name='SDGFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdg_number', models.PositiveSmallIntegerField()),
                ('goal_name', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdg_focuses', to='pages.programinitiative')),
            ],
            options={
                'ordering': ['order', 'sdg_number'],
                'constraints': [models.UniqueConstraint(fields=('initiative', 'sdg_number'), name='unique_initiative_sdg')],
            },
        ),
        migrations.RunPython(seed_program_initiatives, remove_program_initiatives),
    ]
