# Generated by Django 6.0.6 on 2026-08-29

from django.db import migrations, models


def populate_mentorship_session_labels(apps, schema_editor):
    Track = apps.get_model("pages", "MentorshipTrack")

    Track.objects.filter(
        initiative__slug="forge-mentorship-program",
        title="Career Development",
        sessions_label="",
    ).update(sessions_label="4 live sessions")
    Track.objects.filter(
        initiative__slug="forge-mentorship-program",
        title="Entrepreneurship",
        sessions_label="",
    ).update(sessions_label="4 live sessions")
    Track.objects.filter(
        initiative__slug="bloom-360-mentorship-program",
        sessions_label="",
    ).update(sessions_label="4 sessions across weeks 9–12")


def clear_mentorship_session_labels(apps, schema_editor):
    Track = apps.get_model("pages", "MentorshipTrack")
    Track.objects.filter(
        initiative__slug__in=(
            "forge-mentorship-program",
            "bloom-360-mentorship-program",
        )
    ).update(sessions_label="")


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_program_initiatives"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitepagecopy",
            old_name="programs_wings_eyebrow",
            new_name="programs_overview_eyebrow",
        ),
        migrations.RenameField(
            model_name="sitepagecopy",
            old_name="programs_wings_headline",
            new_name="programs_overview_headline",
        ),
        migrations.RenameField(
            model_name="sitepagecopy",
            old_name="programs_wings_body",
            new_name="programs_overview_body",
        ),
        migrations.AddField(
            model_name="sitepagecopy",
            name="programs_conferences_eyebrow",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="sitepagecopy",
            name="programs_conferences_headline",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sitepagecopy",
            name="programs_conferences_body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sitepagecopy",
            name="programs_events_body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mentorshiptrack",
            name="sessions_label",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Public session summary, e.g. '4 live sessions' or "
                    "'4 sessions across weeks 9–12'."
                ),
                max_length=120,
            ),
        ),
        migrations.RunPython(
            populate_mentorship_session_labels,
            clear_mentorship_session_labels,
        ),
    ]
