# Generated by Django 6.0.6 on 2026-08-31 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_event_updated_at_program_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='initiative',
            field=models.ForeignKey(blank=True, help_text='The Programs & Initiatives page this event belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='pages.programinitiative'),
        ),
    ]
