from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.home, name="home"),
    path("reports/", views.reports_view, name="reports"),
    path("reports/export.csv", views.reports_export, name="reports_export"),
    path("messaging/", views.messaging_view, name="messaging"),
    path("messaging/new/", views.campaign_create, name="campaign_create"),
    path("messaging/campaigns/<int:pk>/", views.campaign_detail, name="campaign_detail"),
    path("messaging/campaigns/<int:pk>/send/", views.campaign_send, name="campaign_send"),
    path("messaging/templates/new/", views.message_template_create, name="message_template_create"),
    path("messaging/templates/<int:pk>/", views.message_template_edit, name="message_template_edit"),
    path("content/integrations/", views.integration_settings, name="integration_settings"),
    path("events/", views.events, name="events"),
    path("events/new/", views.event_create, name="event_create"),
    path("events/<int:pk>/", views.event_detail, name="event_detail"),
    path("events/<int:pk>/edit/", views.event_edit, name="event_edit"),
    path("events/<int:pk>/<str:action>/", views.event_action, name="event_action"),
    path("events/<int:event_pk>/registrations/<int:reg_pk>/",
         views.update_registration, name="update_registration"),
    path("donations/", views.donations_view, name="donations"),
    path("donations/reconcile/", views.donations_reconcile, name="donations_reconcile"),
    path("finance/", views.finance_accounting, name="finance_accounting"),
    path("finance/accounting/", views.accounting_core, name="accounting_core"),
    path("finance/accounting/accounts/new/", views.ledger_account_create, name="ledger_account_create"),
    path("finance/accounting/funds/new/", views.fund_create, name="fund_create"),
    path("finance/accounting/periods/new/", views.fiscal_period_create, name="fiscal_period_create"),
    path("finance/accounting/periods/<int:pk>/<str:action>/", views.fiscal_period_action, name="fiscal_period_action"),
    path("finance/accounting/journals/new/", views.journal_create, name="journal_create"),
    path("finance/accounting/journals/<int:pk>/", views.journal_detail, name="journal_detail"),
    path("finance/accounting/journals/<int:pk>/<str:action>/", views.journal_action, name="journal_action"),
    path("finance/accounting/budgets/new/", views.budget_create, name="budget_create"),
    path("finance/accounting/budgets/<int:pk>/<str:action>/", views.budget_action, name="budget_action"),
    path("finance/accounting/reconciliations/new/", views.reconciliation_create, name="reconciliation_create"),
    path("finance/accounting/reconciliations/<int:pk>/approve/", views.reconciliation_action, name="reconciliation_action"),
    path("finance/export.csv", views.finance_export, name="finance_export"),
    path("finance/accounts/new/", views.cash_account_create, name="cash_account_create"),
    path("finance/accounts/<int:pk>/edit/", views.cash_account_edit,
         name="cash_account_edit"),
    path("finance/accounts/<int:pk>/<str:action>/", views.cash_account_action,
         name="cash_account_action"),
    path("finance/cash-movements/new/", views.cash_movement_create,
         name="cash_movement_create"),
    path("finance/cash-movements/<int:pk>/edit/", views.cash_movement_edit,
         name="cash_movement_edit"),
    path("finance/cash-movements/<int:pk>/<str:action>/", views.cash_movement_action,
         name="cash_movement_action"),
    path("finance/expenses/new/", views.expense_create, name="expense_create"),
    path("finance/expenses/<int:pk>/edit/", views.expense_edit, name="expense_edit"),
    path("finance/expenses/<int:pk>/<str:action>/", views.expense_action,
         name="expense_action"),
    path("donations/<int:pk>/", views.donation_detail, name="donation_detail"),
    path("donations/<int:pk>/<str:action>/", views.donation_action,
         name="donation_action"),
    path("applications/", views.applications_view, name="applications"),
    path("applications/<int:pk>/<str:decision>/", views.review_application,
         name="review_application"),
    path("mentorship/", views.mentorship_view, name="mentorship"),
    path("mentorship/new/", views.mentorship_create, name="mentorship_create"),
    path("mentorship/<int:pk>/edit/", views.mentorship_edit, name="mentorship_edit"),
    path("members/", views.members_view, name="members"),
    path("members/<int:pk>/", views.member_detail, name="member_detail"),
    path("programs/", views.programs_manage, name="programs_manage"),
    path("programs/new/", views.program_create, name="program_create"),
    path("programs/<int:pk>/edit/", views.program_edit, name="program_edit"),
    path("programs/<int:pk>/delete/", views.program_delete, name="program_delete"),
    path("resources/", views.resources_manage, name="resources_manage"),
    path("resources/new/", views.resource_create, name="resource_create"),
    path("resources/<int:pk>/edit/", views.resource_edit, name="resource_edit"),
    path("resources/<int:pk>/delete/", views.resource_delete, name="resource_delete"),
    path("speakers/", views.speakers_manage, name="speakers_manage"),
    path("speakers/new/", views.speaker_create, name="speaker_create"),
    path("speakers/<int:pk>/edit/", views.speaker_edit, name="speaker_edit"),
    path("speakers/<int:pk>/delete/", views.speaker_delete, name="speaker_delete"),
    path("leadership/", views.leadership_manage, name="leadership_manage"),
    path("leadership/new/", views.leadership_create, name="leadership_create"),
    path("leadership/<int:pk>/edit/", views.leadership_edit, name="leadership_edit"),
    path("leadership/<int:pk>/delete/", views.leadership_delete, name="leadership_delete"),
    path("content/", views.content_view, name="content"),
    path("content/<str:section>/new/", views.content_create, name="content_create"),
    path("content/<str:section>/<int:pk>/delete/", views.content_delete,
         name="content_delete"),
    path("content/<str:section>/<int:pk>/", views.content_edit, name="content_edit"),
    path("enquiries/", views.enquiries_view, name="enquiries"),
    path("enquiries/messages/<int:pk>/<str:action>/", views.message_action,
         name="message_action"),
    path("enquiries/partners/<int:pk>/<str:action>/", views.partner_action,
         name="partner_action"),
    path("audit/", views.audit_view, name="audit"),
    path("api/analytics/", views.analytics_api, name="analytics_api"),
]
