# Generated by Django 6.0.6 on 2026-07-07 13:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('PROGRAMS', 'Programs'), ('EVENTS', 'Events'), ('MENTORSHIP', 'Mentorship'), ('OUTREACH', 'Humanitarian Outreach'), ('OPERATIONS', 'Operations'), ('MEDIA', 'Media / Communications'), ('TECHNOLOGY', 'Technology'), ('ADMIN', 'Administration'), ('OTHER', 'Other')], db_index=True, default='OPERATIONS', max_length=20)),
                ('payee', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GHS', max_length=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=12)),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(blank=True, max_length=80)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
