# Generated by Django 6.0.6 on 2026-07-07 14:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_expense'),
        ('donations', '0002_donation_note_donation_receipt_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash on hand'), ('BANK', 'Bank account'), ('MOBILE_MONEY', 'Mobile money wallet'), ('PAYMENT_GATEWAY', 'Payment gateway'), ('SAVINGS', 'Savings / reserve'), ('OTHER', 'Other')], db_index=True, default='BANK', max_length=20)),
                ('institution_name', models.CharField(blank=True, max_length=160)),
                ('account_number', models.CharField(blank=True, max_length=80)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='GHS', max_length=8)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_balance_date', models.DateField(default=django.utils.timezone.localdate)),
                ('statement_balance', models.DecimalField(decimal_places=2, default=0, help_text='Most recent bank or cash-count statement balance.', max_digits=12)),
                ('last_reconciled_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=12)),
                ('is_primary', models.BooleanField(default=False)),
                ('accepts_donations', models.BooleanField(default=True)),
                ('pays_expenses', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'account_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Money in'), ('OUT', 'Money out'), ('TRANSFER', 'Transfer')], db_index=True, default='IN', max_length=10)),
                ('category', models.CharField(choices=[('DONATION_CLEARING', 'Donation clearing'), ('EXPENSE_PAYMENT', 'Expense payment'), ('CASH_DEPOSIT', 'Cash deposit'), ('CASH_WITHDRAWAL', 'Cash withdrawal'), ('BANK_CHARGE', 'Bank charge'), ('TRANSFER', 'Internal transfer'), ('OPENING_ADJUSTMENT', 'Opening adjustment'), ('RECONCILIATION', 'Reconciliation adjustment'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=24)),
                ('title', models.CharField(max_length=180)),
                ('counterparty', models.CharField(blank=True, max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GHS', max_length=8)),
                ('movement_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='cash-movements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='dashboard.cashaccount')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('linked_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='donations.donation')),
                ('linked_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='dashboard.expense')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('transfer_account', models.ForeignKey(blank=True, help_text='Destination account for internal transfers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='dashboard.cashaccount')),
            ],
            options={
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
    ]
