# Generated by Django 6.0.6 on 2026-07-10 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_cashaccount_cashmovement'),
        ('pages', '0005_sitebranding_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_provider', models.CharField(choices=[('ARKESEL', 'Arkesel'), ('HUBTEL', 'Hubtel')], default='ARKESEL', max_length=12)),
                ('sms_sender_id', models.CharField(blank=True, default='OIF', max_length=11)),
                ('arkesel_api_key', models.CharField(blank=True, max_length=255)),
                ('arkesel_base_url', models.URLField(blank=True, default='https://sms.arkesel.com/api/v2/sms/send')),
                ('hubtel_client_id', models.CharField(blank=True, max_length=255)),
                ('hubtel_client_secret', models.CharField(blank=True, max_length=255)),
                ('hubtel_base_url', models.URLField(blank=True, default='https://smsc.hubtel.com/v1/messages/send')),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('whatsapp_access_token', models.CharField(blank=True, max_length=255)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, max_length=100)),
                ('whatsapp_business_number', models.CharField(blank=True, max_length=32)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_from_name', models.CharField(blank=True, default='OIF', max_length=120)),
                ('paystack_enabled', models.BooleanField(default=False)),
                ('paystack_public_key', models.CharField(blank=True, max_length=255)),
                ('paystack_secret_key', models.CharField(blank=True, max_length=255)),
                ('paystack_webhook_secret', models.CharField(blank=True, max_length=255)),
                ('paystack_demo_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Integration settings',
            },
        ),
        migrations.CreateModel(
            name='MessageCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('ALL', 'Email, SMS and WhatsApp')], max_length=12)),
                ('audience', models.CharField(choices=[('ALL_MEMBERS', 'All active members'), ('MARKETING', 'Marketing opt-ins'), ('ROLE', 'Members in selected role'), ('EVENT', 'Event registrants'), ('NEWSLETTER', 'Newsletter subscribers'), ('CUSTOM', 'Custom recipients')], max_length=20)),
                ('role', models.CharField(blank=True, choices=[('ADMIN', 'Super Administrator'), ('GLOBAL_LEAD', 'Global Lead'), ('EXEC_DIRECTOR', 'Executive Director'), ('DIRECTOR', 'Director / Staff'), ('DIR_PROGRAMS', 'Director of Programmes'), ('DIR_OPS', 'Director of Operations & Volunteer Engagement'), ('DIR_COMMS', 'Director of Communications, Media & Digital'), ('DIR_PARTNERSHIPS', 'Director of Partnerships & Resource Mobilisation'), ('FINANCE', 'Finance / Donations Manager'), ('CONTENT_EDITOR', 'Content Editor'), ('EVENT_MANAGER', 'Event Manager'), ('MENTOR', 'Mentor'), ('VOLUNTEER', 'Volunteer'), ('APPLICANT', 'Applicant'), ('DONOR', 'Donor'), ('MEMBER', 'Member')], max_length=20)),
                ('custom_recipients', models.TextField(blank=True, help_text='One email address or phone number per line.')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(help_text='Use {name}, {first_name}, {email}, {phone}, and {org_name} placeholders.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('PARTIAL', 'Partially sent'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_campaigns', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MessageDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('ALL', 'Email, SMS and WhatsApp')], max_length=12)),
                ('recipient', models.CharField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=12)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='dashboard.messagecampaign')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='dashboard_m_campaig_740b54_idx')],
            },
        ),
    ]
