# Generated by Django 6.0.6 on 2026-07-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_integrationsettings_messagecampaign_messagetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='paystack_use_cms_configuration',
            field=models.BooleanField(default=False, help_text='Use the Paystack values below instead of environment variables.'),
        ),
    ]
