# Generated by Django 6.0.6 on 2026-07-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_opt_in',
            field=models.BooleanField(default=False, help_text='Consented to newsletters / updates.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Super Administrator'), ('GLOBAL_LEAD', 'Global Lead'), ('EXEC_DIRECTOR', 'Executive Director'), ('DIRECTOR', 'Director / Staff'), ('DIR_PROGRAMS', 'Director of Programmes'), ('DIR_OPS', 'Director of Operations & Volunteer Engagement'), ('DIR_COMMS', 'Director of Communications, Media & Digital'), ('DIR_PARTNERSHIPS', 'Director of Partnerships & Resource Mobilisation'), ('FINANCE', 'Finance / Donations Manager'), ('CONTENT_EDITOR', 'Content Editor'), ('EVENT_MANAGER', 'Event Manager'), ('MENTOR', 'Mentor'), ('VOLUNTEER', 'Volunteer'), ('APPLICANT', 'Applicant'), ('DONOR', 'Donor'), ('MEMBER', 'Member')], db_index=True, default='MEMBER', max_length=20),
        ),
    ]
