# Generated by Django 6.0.6 on 2026-07-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_newslettersubscriber_mentorshipenrollment_cohort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='accessibility_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='attendance_mode',
            field=models.CharField(choices=[('IN_PERSON', 'In person'), ('VIRTUAL', 'Virtual'), ('EITHER', 'Either / flexible')], default='EITHER', max_length=12),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='dietary_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='organisation',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='question',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='role_title',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
