# Generated by Django 6.0.6 on 2026-06-08 10:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=160)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='GHS', max_length=8)),
                ('channel', models.CharField(choices=[('MOMO', 'Mobile Money'), ('CARD', 'Card'), ('BANK', 'Bank Transfer')], default='MOMO', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed')], db_index=True, default='SUCCESS', max_length=8)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('campaign', models.CharField(blank=True, default='General Fund', max_length=120)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
