# Generated by Django 6.0.6 on 2026-07-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='note',
            field=models.CharField(blank=True, help_text='Optional message from the donor.', max_length=300),
        ),
        migrations.AddField(
            model_name='donation',
            name='receipt_sent',
            field=models.BooleanField(default=False),
        ),
    ]
